version: "3.8"
services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./data:/data
      - ./music:/music
    env_file:
      - .env.example
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=America/Sao_Paulo
